config/routes.rb
GbcStrmwdJcohair::Application.routes.draw do
  get "later/index"

  get "newspaper/index"

  get "funeral/index"

  get "farewell/index"

  get "testimony/index"

  get "youtube/index"

  get "early/index"

  get "pics/index"

 authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users

  resources :grace_associates
  resources :pics
  resources :early
  resources :youtube
  resources :testimony
  resources :farewell
  resources :funeral
  resources :newspaper
  resources :later
  
  match '/early' => 'early#index', :as => 'early'
  match '/youtube' => 'youtube#index', :as => 'youtube'
  match '/testimony' => 'testimony#index', :as => 'testimony'
  match '/farewell' => 'farewell#index', :as => 'farewell'
  match '/funeral' => 'funeral#index', :as => 'funeral'
  match '/images' => 'assets#images', :as => 'images'
  match '/newspaper' => 'newspaper#index', :as => 'newspaper'
  match '/later' => 'later#index', :as => 'later'

   root :to => 'home#index'

end

app/models/grace_associate.rb
class GraceAssociate < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
end

app/controllers/grace_associates_controller.rb
class GraceAssociatesController < ApplicationController
  # GET /grace_associates
  # GET /grace_associates.json
  def index
    @grace_associates = GraceAssociate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grace_associates }
    end
  end

  # GET /grace_associates/1
  # GET /grace_associates/1.json
  def show
    @grace_associate = GraceAssociate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grace_associate }
    end
  end

  # GET /grace_associates/new
  # GET /grace_associates/new.json
  def new
    @grace_associate = GraceAssociate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grace_associate }
    end
  end

  # GET /grace_associates/1/edit
  def edit
    @grace_associate = GraceAssociate.find(params[:id])
  end

  # POST /grace_associates
  # POST /grace_associates.json
  def create
    @grace_associate = GraceAssociate.new(params[:grace_associate])

    respond_to do |format|
      if @grace_associate.save
        format.html { redirect_to @grace_associate, notice: 'Grace associate was successfully created.' }
        format.json { render json: @grace_associate, status: :created, location: @grace_associate }
      else
        format.html { render action: "new" }
        format.json { render json: @grace_associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grace_associates/1
  # PUT /grace_associates/1.json
  def update
    @grace_associate = GraceAssociate.find(params[:id])

    respond_to do |format|
      if @grace_associate.update_attributes(params[:grace_associate])
        format.html { redirect_to @grace_associate, notice: 'Grace associate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grace_associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grace_associates/1
  # DELETE /grace_associates/1.json
  def destroy
    @grace_associate = GraceAssociate.find(params[:id])
    @grace_associate.destroy

    respond_to do |format|
      format.html { redirect_to grace_associates_url }
      format.json { head :no_content }
    end
  end
end

app/views/grace_associates/_form.html.erb
<%= form_for @grace_associate, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                grace_associates_path, :class => 'btn' %>
  </div>
<% end %>

app/views/grace_associates/edit.html.erb
<%- model_class = GraceAssociate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grace_associates/index.html.erb
<%- model_class = GraceAssociate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:password_confirmation) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @grace_associates.each do |grace_associate| %>
      <tr>
        <td><%= link_to grace_associate.id, grace_associate_path(grace_associate) %></td>
        <td><%= grace_associate.name %></td>
        <td><%= grace_associate.email %></td>
        <td><%= grace_associate.password %></td>
        <td><%= grace_associate.password_confirmation %></td>
        <td><%=l grace_associate.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_grace_associate_path(grace_associate), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      grace_associate_path(grace_associate),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_grace_associate_path,
            :class => 'btn btn-primary' %>

app/views/grace_associates/new.html.erb
<%- model_class = GraceAssociate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grace_associates/show.html.erb
<%- model_class = GraceAssociate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @grace_associate.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @grace_associate.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @grace_associate.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password_confirmation) %>:</strong></dt>
  <dd><%= @grace_associate.password_confirmation %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              grace_associates_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_grace_associate_path(@grace_associate), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              grace_associate_path(@grace_associate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>